### ISSUE TITLE
Sign Up Page Design

### ISSUE THREAD

**Issue by Vishal-raj-1** [Gautam-Arora24/bloodInNeed-frontend#1]
Left hand side image and already have account section need less padding. Here your image and that section overlap with footer. Have a look:
![hgg](https://user-images.githubusercontent.com/59874304/100967672-ce072880-3555-11eb-9914-f7765fa4c2a7.JPG)

**Comment by Gautam-Arora24** [comment]
Would you like to work on this issue?

**Comment by Vishal-raj-1** [comment]
As of Now, I am not free. I am just sharing the problem. You have given verticle-align:center; style for that image. Because of that this terrible thing happens:
![Uploading check.gif…]()
